# -*- coding: utf-8 -*-
"""Untitled56.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1La52VCgoMIDUEcfk_93vIfdjJsWN8GOj
"""

import os
import json
import zipfile
import random
import numpy as np
import cv2
import torch
import torchvision
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import seaborn as sns

from torch.utils.data import Dataset, DataLoader
import torchvision.transforms.functional as F
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torchvision.models.detection.mask_rcnn import MaskRCNNPredictor
from torchvision.ops import box_iou
from pycocotools import mask as mask_utils

# ==========================================
# CONFIGURATION
# ==========================================
DATA_DIR = './hw3-data-release'
OUTPUT_DIR = './outputs'
MODEL_WEIGHTS_PATH = os.path.join(OUTPUT_DIR, 'maskrcnn_baseline_20ep.pth')
NUM_EPOCHS = 20

# Ensure output directory exists
os.makedirs(OUTPUT_DIR, exist_ok=True)
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

# ==========================================
# DATASETS
# ==========================================
class MedicalCellDatasetSafe(Dataset):
    """Dataset for training with safe aspect-ratio resizing to prevent OOM."""
    def __init__(self, root_dir, split='train', max_dim=1333):
        self.root_dir = root_dir
        self.split = split
        self.max_dim = max_dim
        self.split_dir = os.path.join(root_dir, 'train')
        self.items = [d for d in os.listdir(self.split_dir) if os.path.isdir(os.path.join(self.split_dir, d))]

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx):
        folder_name = self.items[idx]
        img_folder = os.path.join(self.split_dir, folder_name)
        img_path = os.path.join(img_folder, 'image.tif')

        img = cv2.imread(img_path, cv2.IMREAD_COLOR)
        h, w = img.shape[:2]

        scale = 1.0
        if max(h, w) > self.max_dim:
            scale = self.max_dim / float(max(h, w))
            new_w, new_h = int(w * scale), int(h * scale)
            img = cv2.resize(img, (new_w, new_h), interpolation=cv2.INTER_LINEAR)

        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = F.to_tensor(img).float()

        masks, labels, boxes = [], [], []
        for class_id in range(1, 5):
            mask_path = os.path.join(img_folder, f'class{class_id}.tif')
            if os.path.exists(mask_path):
                class_mask = cv2.imread(mask_path, cv2.IMREAD_UNCHANGED)
                if scale != 1.0:
                    class_mask = cv2.resize(class_mask, (new_w, new_h), interpolation=cv2.INTER_NEAREST)

                obj_ids = np.unique(class_mask)
                obj_ids = obj_ids[obj_ids != 0]

                for obj_id in obj_ids:
                    instance_mask = (class_mask == obj_id)
                    pos = np.where(instance_mask)
                    if len(pos[0]) == 0:
                        continue

                    xmin, xmax = np.min(pos[1]), np.max(pos[1])
                    ymin, ymax = np.min(pos[0]), np.max(pos[0])
                    if xmin == xmax or ymin == ymax:
                        continue

                    masks.append(instance_mask)
                    boxes.append([xmin, ymin, xmax, ymax])
                    labels.append(class_id)

        target = {}
        if len(boxes) > 0:
            target["boxes"] = torch.as_tensor(boxes, dtype=torch.float32)
            target["labels"] = torch.as_tensor(labels, dtype=torch.int64)
            target["masks"] = torch.as_tensor(np.array(masks), dtype=torch.uint8)
        else:
            target["boxes"] = torch.zeros((0, 4), dtype=torch.float32)
            target["labels"] = torch.zeros((0,), dtype=torch.int64)
            target["masks"] = torch.zeros((0, img.shape[1], img.shape[2]), dtype=torch.uint8)

        return img, target


class MedicalCellTestDataset(Dataset):
    """Dataset for CodaBench inference."""
    def __init__(self, root_dir):
        self.split_dir = os.path.join(root_dir, 'test_release')
        self.items = [f for f in os.listdir(self.split_dir) if f.endswith('.tif')]

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx):
        file_name = self.items[idx]
        img_path = os.path.join(self.split_dir, file_name)
        img = cv2.imread(img_path, cv2.IMREAD_COLOR)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = F.to_tensor(img).float()
        return img, file_name


def collate_fn(batch):
    return tuple(zip(*batch))

def encode_mask(binary_mask):
    arr = np.asfortranarray(binary_mask).astype(np.uint8)
    rle = mask_utils.encode(arr)
    if isinstance(rle['counts'], bytes):
        rle['counts'] = rle['counts'].decode('utf-8')
    return rle


# ==========================================
# MODEL ARCHITECTURE
# ==========================================
def get_model_instance_segmentation(num_classes):
    model = torchvision.models.detection.maskrcnn_resnet50_fpn(weights='DEFAULT')
    in_features = model.roi_heads.box_predictor.cls_score.in_features
    model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)
    in_features_mask = model.roi_heads.mask_predictor.conv5_mask.in_channels
    model.roi_heads.mask_predictor = MaskRCNNPredictor(in_features_mask, 256, num_classes)
    return model


# ==========================================
# TRAINING PIPELINE
# ==========================================
def train_model(model, train_loader):
    print(f"Starting {NUM_EPOCHS}-Epoch Training...")
    params = [p for p in model.parameters() if p.requires_grad]
    optimizer = torch.optim.SGD(params, lr=0.005, momentum=0.9, weight_decay=0.0005)
    lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=5, gamma=0.1)

    model.train()
    for epoch in range(NUM_EPOCHS):
        epoch_loss = 0
        for images, targets in train_loader:
            images = list(image.to(device) for image in images)
            targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

            loss_dict = model(images, targets)
            losses = sum(loss for loss in loss_dict.values())

            optimizer.zero_grad()
            losses.backward()
            optimizer.step()
            epoch_loss += losses.item()

        lr_scheduler.step()
        print(f"Epoch [{epoch+1}/{NUM_EPOCHS}] Loss: {epoch_loss/len(train_loader):.4f}")

    torch.save(model.state_dict(), MODEL_WEIGHTS_PATH)
    print(f"Model saved locally to {MODEL_WEIGHTS_PATH}")


# ==========================================
# INFERENCE PIPELINE (CodaBench Submission)
# ==========================================
def generate_submission(model, test_dataset):
    print("Generating CodaBench Submission...")
    mapping_file_path = os.path.join(DATA_DIR, 'test_image_name_to_ids.json')
    with open(mapping_file_path, 'r') as f:
        mapping_data = json.load(f)

    name_to_id = {os.path.splitext(item['file_name'])[0]: int(item['id']) for item in mapping_data}

    submission_results = []
    model.eval()
    with torch.no_grad():
        for i in range(len(test_dataset)):
            img, file_name = test_dataset[i]
            base_name = os.path.splitext(file_name)[0]
            img_id = name_to_id.get(base_name)
            if img_id is None:
                continue

            out = model([img.to(device)])[0]

            boxes = out['boxes'].cpu().numpy()
            scores = out['scores'].cpu().numpy()
            labels = out['labels'].cpu().numpy()
            masks = out['masks'].cpu().numpy()

            for j in range(len(scores)):
                # Retaining the 0.05 threshold to maximize COCO mAP recall
                if scores[j] > 0.05:
                    mask_binary = (masks[j, 0] > 0.5).astype(np.uint8)
                    rle_segmentation = encode_mask(mask_binary)

                    xmin, ymin, xmax, ymax = boxes[j]
                    width = max(float(xmax - xmin), 1.0)
                    height = max(float(ymax - ymin), 1.0)

                    pred_dict = {
                        "image_id": int(img_id),
                        "category_id": int(labels[j]),
                        "bbox": [float(xmin), float(ymin), float(width), float(height)],
                        "score": float(scores[j]),
                        "segmentation": rle_segmentation
                    }
                    submission_results.append(pred_dict)

    json_filename = os.path.join(OUTPUT_DIR, 'test-results.json')
    zip_filename = os.path.join(OUTPUT_DIR, 'DL_HW3_Submission.zip')

    with open(json_filename, 'w') as f:
        json.dump(submission_results, f)
    with zipfile.ZipFile(zip_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
        # Zip must contain 'test-results.json' exactly, without folder paths
        zipf.write(json_filename, arcname='test-results.json')
    print(f"DONE! Submission saved as: {zip_filename}")


# ==========================================
# ADDITIONAL EXPERIMENTS
# ==========================================
def run_additional_experiments(model, train_dataset):
    print("Running Additional Experiments for Report...")
    eval_loader = DataLoader(train_dataset, batch_size=1, shuffle=True, num_workers=0, collate_fn=collate_fn)
    model.eval()

    all_images, all_targets, all_outputs = [], [], []

    with torch.no_grad():
        for i, (images, targets) in enumerate(eval_loader):
            if i >= 15:
                break
            images = list(img.to(device) for img in images)
            targets = [{k: v.to(device) for k, v in t.items()} for t in targets]
            outputs = model(images)

            all_images.append(images[0].cpu())
            all_targets.append({k: v.cpu() for k, v in targets[0].items()})
            all_outputs.append({k: v.cpu() for k, v in outputs[0].items()})

    # --- 1. Threshold Ablation Curve ---
    print("1/3 Generating Threshold Impact Curve...")
    thresholds = [0.05, 0.20, 0.35, 0.50, 0.65, 0.80, 0.95]
    avg_preds = [sum(np.sum((out['scores'].numpy() > t)) for out in all_outputs) / len(all_outputs) for t in thresholds]

    plt.figure(figsize=(8, 5))
    plt.plot(thresholds, avg_preds, marker='o', color='b', linewidth=2)
    plt.axvline(x=0.50, color='r', linestyle='--', label='0.50 Analysis Threshold')
    plt.title('Impact of Confidence Threshold on False Positives')
    plt.xlabel('Confidence Threshold')
    plt.ylabel('Average Predictions per Image')
    plt.grid(True, linestyle=':', alpha=0.7)
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, 'Exp1_Threshold.png'), dpi=300)
    plt.close()

    # --- 2. IoU Confusion Matrix ---
    print("2/3 Generating IoU Confusion Matrix...")
    conf_matrix = np.zeros((5, 5), dtype=np.int32)
    iou_thresh = 0.50

    for target, output in zip(all_targets, all_outputs):
        true_boxes, true_labels = target['boxes'], target['labels']
        keep = output['scores'] > 0.50
        pred_boxes, pred_labels = output['boxes'][keep], output['labels'][keep]

        if len(true_boxes) == 0 or len(pred_boxes) == 0:
            for tl in true_labels: conf_matrix[tl.item(), 0] += 1
            for pl in pred_labels: conf_matrix[0, pl.item()] += 1
            continue

        ious = box_iou(true_boxes, pred_boxes)
        matched = set()

        for true_idx, true_lbl in enumerate(true_labels):
            best_iou, best_pred = 0, -1
            for pred_idx, pred_lbl in enumerate(pred_labels):
                if pred_idx in matched: continue
                if ious[true_idx, pred_idx] > best_iou:
                    best_iou, best_pred = ious[true_idx, pred_idx], pred_idx

            if best_iou >= iou_thresh:
                matched.add(best_pred)
                conf_matrix[true_lbl.item(), pred_labels[best_pred].item()] += 1
            else:
                conf_matrix[true_lbl.item(), 0] += 1

        for pred_idx, pred_lbl in enumerate(pred_labels):
            if pred_idx not in matched:
                conf_matrix[0, pred_lbl.item()] += 1

    plt.figure(figsize=(8, 6))
    class_names = ['Background', 'Class 1', 'Class 2', 'Class 3', 'Class 4']
    sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
    plt.ylabel('True Target Class')
    plt.xlabel('Model Predicted Class')
    plt.title('Instance Segmentation Confusion Matrix (IoU > 0.5)')
    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, 'Exp2_Matrix.png'), dpi=300)
    plt.close()

    # --- 3. Visual Ground Truth vs. Prediction ---
    print("3/3 Generating Visual Comparison...")
    img_np = np.clip(all_images[0].permute(1, 2, 0).numpy(), 0, 1)
    target, out = all_targets[0], all_outputs[0]

    fig, axes = plt.subplots(1, 2, figsize=(14, 7))
    colors = {1: 'red', 2: 'green', 3: 'blue', 4: 'yellow'}

    axes[0].imshow(img_np)
    axes[0].set_title("Ground Truth")
    axes[0].axis('off')
    for box, label in zip(target['boxes'].numpy(), target['labels'].numpy()):
        axes[0].add_patch(patches.Rectangle((box[0], box[1]), box[2]-box[0], box[3]-box[1],
                          linewidth=2, edgecolor=colors.get(label, 'white'), facecolor='none'))

    axes[1].imshow(img_np)
    axes[1].set_title("Predictions (>50% Confidence)")
    axes[1].axis('off')
    for box, label, score in zip(out['boxes'].numpy(), out['labels'].numpy(), out['scores'].numpy()):
        if score > 0.50:
            axes[1].add_patch(patches.Rectangle((box[0], box[1]), box[2]-box[0], box[3]-box[1],
                              linewidth=2, edgecolor=colors.get(label, 'white'), facecolor='none'))

    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, 'Exp3_Visual.png'), dpi=300)
    plt.close()
    print("All experiments saved to outputs directory.")


# ==========================================
# MAIN EXECUTION
# ==========================================
if __name__ == '__main__':
    # 1. Initialize Datasets
    train_ds = MedicalCellDatasetSafe(DATA_DIR, split='train')
    train_dl = DataLoader(train_ds, batch_size=1, shuffle=True, num_workers=2, collate_fn=collate_fn)
    test_ds = MedicalCellTestDataset(DATA_DIR)

    # 2. Initialize Model
    net = get_model_instance_segmentation(num_classes=5)
    net.to(device)

    # 3. Train Model
    train_model(net, train_dl)

    # 4. Generate CodaBench Submission
    generate_submission(net, test_ds)

    # 5. Generate Graphs for Report
    run_additional_experiments(net, train_ds)